x<-read.table("http://www.math.unm.edu/~luyan/ADA118/school.txt" ,header = TRUE)
pairs(x[,2:4])
cor.test(x$verbal,x$SES,conf.level = 1-0.0167)
cor.test(x$verbal,x$salary,conf.level = 1-0.0167)
cor.test(x$salary,x$SES,conf.level = 1-0.0167)
boxplot(x$verbal,main= "verbal")
boxplot(x$salary, main="salary")
boxplot(x$SES, main="SES")
hist(x$verbal,main= "verbal")
hist(x$salary, main="salary")
hist(x$SES, main="SES")
mean(x$verbal,main= "verbal")
median(x$verbal,main= "verbal")
mean(x$salary, main="salary")
median(x$salary, main="salary")
mean(x$SES, main="SES")
median(x$SES, main="SES")
reg<-lm(x$verbal~x$SES)
summary(reg)