install.packages("BSDA")
library(BSDA)
install.packages("car")
library(car)
install.packages("nortest")
library(nortest)
d1<- read.table("http://www.math.unm.edu/~luyan/ADA118/guinea.csv", header= TRUE)
t_crit <- abs(qt(0.05/2,71))
se_1<- sd(d1$hours)/sqrt(72)
ci_min <- mean(d1$hours)-(t_crit*se_1)
ci_max <- mean(d1$hours)+(t_crit*se_1)
ci <- c(ci_min,ci_max) 
hist(d1$hours)
qqnorm(d1$hours)
qqline(d1$hours)
qqPlot(d1$hours)
boxplot(d1$hours)
mean(d1$hours)
median(d1$hours)
SIGN.test(d1$hours)
log_d1<-log(d1$hours)
t.test(log_d1)
SIGN.test(log_d1)